Add scripts for log generation and fixes
Signed-off-by: Sri Vignesh <sselvan@redhat.com>

diff --git a/pipelines/pipeline-network.yaml b/pipelines/pipeline-network.yaml
--- a/pipelines/pipeline-network.yaml
+++ b/pipelines/pipeline-network.yaml
@@ -1,10 +1,16 @@
+apiVersion: v1
+kind: Namespace
+metadata:
+  name: test-network
+spec: {}
+---
 apiVersion: tekton.dev/v1beta1
 kind: PipelineRun
 metadata:
   generateName: network-pipeline-
-  namespace: default
+  namespace: test-network
   labels:
-   pipelines.appstudio.openshift.io/type: release
+   pipelines.appstudio.openshift.io/type: test
 spec:
   pipelineSpec:
     tasks:
@@ -74,6 +80,30 @@ spec:
                     echo "File Not Found"
                     exit 1
                 fi
+      - name: upload-50mb
+        taskSpec:
+          metadata:
+            labels:
+              app: "upload-50mb"
+          steps:
+            - name: upload-50mb
+              image: registry.access.redhat.com/ubi9/ubi
+              script: |
+                #!/usr/bin/env bash
+                mkdir /tests
+                head -c 50M < /dev/urandom > /tests/random-upload-50.log || exit 1
+                if [ ! -f /tests/random-upload-50.log ]; then
+                    echo "User workload Generation Failed"
+                    exit 1
+                fi
+                echo "Uploading"
+                curl -F "file=@/tests/random-upload-50.log" https://tmpfiles.org/api/v1/upload
+                if [ $? -eq 0 ]; then
+                    echo "Success"
+                else
+                    echo "Failure $?"
+                    exit 1
+                fi
       - name: upload-95mb
         taskSpec:
           metadata:
@@ -87,35 +117,11 @@ spec:
                 mkdir /tests
                 head -c 95M < /dev/urandom > /tests/random-upload-95.log || exit 1
                 if [ ! -f /tests/random-upload-95.log ]; then
-                    echo "Log Generation Failed"
+                    echo "User workload Generation Failed"
                     exit 1
                 fi
                 echo "Uploading"
                 curl -F "file=@/tests/random-upload-95.log" https://tmpfiles.org/api/v1/upload
-                if [ $? -eq 0 ]; then
-                    echo "Success"
-                else
-                    echo "Failure $?"
-                    exit 1
-                fi
-      - name: upload-50mb
-        taskSpec:
-          metadata:
-            labels:
-              app: "upload-50mb"
-          steps:
-            - name: upload-50mb
-              image: registry.access.redhat.com/ubi9/ubi
-              script: |
-                #!/usr/bin/env bash
-                mkdir /tests
-                head -c 50M < /dev/urandom > /tests/random-upload-50.log || exit 1
-                if [ ! -f /tests/random-upload-95.log ]; then
-                    echo "Log Generation Failed"
-                    exit 1
-                fi
-                echo "Uploading"
-                curl -F "file=@/tests/random-upload-50.log" https://tmpfiles.org/api/v1/upload
                 if [ $? -eq 0 ]; then
                     echo "Success"
                 else
